services:
  nginx:
    image: nginx:alpine
    ports:
      - "6080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3

  app1:
    build: .
    environment:
      - INSTANCE_NUMBER=1

  app2:
    build: .
    environment:
      - INSTANCE_NUMBER=2

  app3:
    build: .
    environment:
      - INSTANCE_NUMBER=3